openapi: '3.0.3'
info:
  title: 書籍管理システム
  version: '1.0'
servers:
  - url: https://localhost:8080/
tags:
  - name: book
    description: 書籍情報関連処理
  - name: user
    description: ユーザ関連の処理
paths:
  /book:
    get:
      tags:
        - book
      summary: 書籍情報取得
      description: 指定IDの書籍の情報を取得する
      operationId: getBook
      parameters:
        - name: id
          in: query
          description: 単一の書籍ID（単一クエリ用、検索条件と同時指定不可）
          required: false
          schema:
            type: integer
            format: int64
            minimum: 1
            example: 1
        - name: title
          in: query
          description: 書籍タイトル（部分一致フィルタ、単一クエリと同時指定不可）
          required: false
          schema:
            type: string
            nullable: true
            example: 星を継ぐもの
        - name: titleKana
          in: query
          description: 書籍タイトルのカタカナ表記（部分一致フィルタ、単一クエリと同時指定不可）
          required: false
          schema:
            type: string
            nullable: true
            example: ホシヲツグモノ
        - name: author
          in: query
          description: 著者名（部分一致フィルタ、単一クエリと同時指定不可）
          required: false
          schema:
            type: string
            nullable: true
            example: ジェイムズ・P・ホーガン
        - name: publisherId
          in: query
          description: 出版社ID（フィルタ、単一クエリと同時指定不可）
          required: false
          schema:
            type: integer
            format: int64
            nullable: true
            minimum: 1
            example: 1
        - name: userId
          in: query
          description: ユーザーID（フィルタ、単一クエリと同時指定不可）
          required: false
          schema:
            type: integer
            format: int64
            nullable: true
            minimum: 1
            example: 1
        - name: pageSize
          in: query
          description: 1ページあたりの件数（必須、条件指定クエリ用）
          required: false
          schema:
            type: integer
            format: int32
            minimum: 1
            example: 10
        - name: currentPage
          in: query
          description: 現在のページ番号（必須、条件指定クエリ用）
          required: false
          schema:
            type: integer
            format: int32
            minimum: 1
            example: 1
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/BookView'
                  - type: array
                    items:
                      $ref: '#/components/schemas/BookView'
              examples:
                singleBook:
                  summary: 単一書籍の取得例
                  value:
                    id: 1
                    title: 星を継ぐもの
                    titleKana: ホシヲツグモノ
                    author: ジェイムズ・P・ホーガン
                    publisherId: 1
                    publisherName: 岩波書店
                    userId: 1
                    userName: 神里 綾華
                    createdAt: '2025-04-24T07:22:13Z'
                    updatedAt: '2025-04-24T07:22:13Z'
                bookList:
                  summary: 条件指定による書籍リストの取得例
                  value:
                    - id: 1
                      title: 星を継ぐもの
                      titleKana: ホシヲツグモノ
                      author: ジェイムズ・P・ホーガン
                      publisherId: 1
                      publisherName: 岩波書店
                      userId: 1
                      userName: 神里 綾華
                      createdAt: '2025-04-24T07:22:13Z'
                      updatedAt: '2025-04-24T07:22:13Z'
                    - id: 2
                      title: ガニメデの優しい巨人
                      titleKana: ガニメデノヤサシイキョジン
                      author: ジェイムズ・P・ホーガン
                      publisherId: 1
                      publisherName: 岩波書店
                      userId: 2
                      userName: 山田 太郎
                      createdAt: '2025-04-25T08:30:00Z'
                      updatedAt: '2025-04-25T08:30:00Z'
        '404':
          description: 指定IDの書籍が見つかりません
          content:
            application/json: {}
        default:
          description: 予想外のエラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      tags:
        - book
      summary: 書籍情報登録
      description: 新たに書籍の情報を登録する
      operationId: registerBook
      requestBody:
        description: 書籍情報
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookCreate'
            examples:
              singleBookCreate:
                summary: 単一書籍登録のリクエスト例
                value:
                  title: 星を継ぐもの
                  titleKana: ホシヲツグモノ
                  author: ジェイムズ・P・ホーガン
                  publisherId: 1
                  userId: 1
      responses:
        '204':
          description: OK
          content:
            application/json:
              examples:
                success:
                  summary: 単一書籍登録成功例
                  value: {}
        default:
          description: 予想外のエラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      tags:
        - book
      summary: 書籍情報削除
      description: 指定IDの書籍情報を削除する
      operationId: deleteBook
      parameters:
        - name: id
          in: query
          description: 書籍ID
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        '204':
          description: OK
          content:
            application/json: {}
        default:
          description: 予想外のエラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      tags:
        - book
      summary: 書籍情報更新
      description: 指定IDの書籍情報を更新する
      operationId: updateBook
      parameters:
        - name: id
          in: query
          description: 書籍ID
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1
      requestBody:
        description: 書籍情報
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookUpdate'
      responses:
        '204':
          description: NO CONTENT
          content:
            application/json: {}
        default:
          description: 予想外のエラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /book/batch:
    post:
      tags:
        - book
      summary: 書籍情報一括登録
      description: 複数の書籍情報を一括で登録する
      operationId: registerBooks
      requestBody:
        description: 書籍情報のリスト
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/BookCreate'
            examples:
              batchBookCreate:
                summary: 複数書籍登録のリクエスト例
                value:
                  - title: 星を継ぐもの
                    titleKana: ホシヲツグモノ
                    author: ジェイムズ・P・ホーガン
                    publisherId: 1
                    userId: 1
                  - title: ガニメデの優しい巨人
                    titleKana: ガニメデノヤサシイキョジン
                    author: ジェイムズ・P・ホーガン
                    publisherId: 1
                    userId: 2
      responses:
        '204':
          description: OK
          content:
            application/json:
              examples:
                success:
                  summary: 複数書籍登録成功例
                  value: {}
        default:
          description: 予想外のエラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      tags:
        - book
      summary: 書籍情報一括削除
      description: 指定された複数の書籍IDに基づいて書籍情報を一括で削除する
      operationId: deleteBooks
      requestBody:
        description: 削除する書籍IDのリスト
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BooksDelete'
            examples:
              batchDelete:
                summary: 複数書籍削除のリクエスト例
                value:
                  ids:
                    - 1
                    - 2
      responses:
        '204':
          description: OK
          content:
            application/json:
              examples:
                success:
                  summary: 複数書籍削除成功例
                  value: {}
        default:
          description: 予想外のエラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      tags:
        - book
      summary: 書籍情報一括更新
      description: 複数の書籍情報を一括で更新する
      operationId: updateBooks
      requestBody:
        description: 更新する書籍情報のリスト
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/BookUpdate'
            examples:
              batchUpdate:
                summary: 複数書籍更新のリクエスト例
                value:
                  - id: 1
                    title: 星を継ぐもの（改訂版）
                    titleKana: ホシヲツグモノカイテイバン
                    author: ジェイムズ・P・ホーガン
                    publisherId: 1
                    userId: 1
                  - id: 2
                    title: ガニメデの優しい巨人（改訂版）
                    titleKana: ガニメデノヤサシイキョジンカイテイバン
                    author: ジェイムズ・P・ホーガン
                    publisherId: 1
                    userId: 2
      responses:
        '204':
          description: OK
          content:
            application/json:
              examples:
                success:
                  summary: 複数書籍更新成功例
                  value: {}
        default:
          description: 予想外のエラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Book:
      type: object
      properties:
        id:
          type: integer
          format: int64
          minimum: 1
          example: 1
        title:
          type: string
          example: 星を継ぐもの
        titleKana:
          type: string
          example: ホシヲツグモノ
        author:
          type: string
          example: ジェイムズ・P・ホーガン
        publisherId:
          type: integer
          format: int64
          minimum: 1
          example: 1
        userId:
          type: integer
          format: int64
          minimum: 1
          example: 1
        createdAt:
          type: string
          format: date-time
          example: '2025-04-24T07:22:13Z'
        updatedAt:
          type: string
          format: date-time
          example: '2025-04-24T07:22:13Z'
      required:
        - id
        - createdAt
        - updatedAt
    BookView:
      type: object
      properties:
        id:
          type: integer
          format: int64
          minimum: 1
          example: 1
        title:
          type: string
          example: 星を継ぐもの
        titleKana:
          type: string
          example: ホシヲツグモノ
        author:
          type: string
          example: ジェイムズ・P・ホーガン
        publisherId:
          type: integer
          format: int64
          minimum: 1
          example: 1
        publisherName:
          type: string
          example: 岩波書店
        userId:
          type: integer
          format: int64
          minimum: 1
          example: 1
        userName:
          type: string
          example: 神里 綾華
        createdAt:
          type: string
          format: date-time
          example: '2025-04-24T07:22:13Z'
        updatedAt:
          type: string
          format: date-time
          example: '2025-04-24T07:22:13Z'
      required:
        - id
        - createdAt
        - updatedAt
    BookCreate:
      type: object
      description: 書籍情報登録用のデータオブジェクト
      properties:
        title:
          type: string
          example: 星を継ぐもの
        titleKana:
          type: string
          example: ホシヲツグモノ
        author:
          type: string
          example: ジェイムズ・P・ホーガン
        publisherId:
          type: integer
          format: int64
          minimum: 1
          example: 1
        userId:
          type: integer
          format: int64
          minimum: 1
          example: 1
      required:
        - title
        - titleKana
        - author
        - publisherId
        - userId
    BookUpdate:
      type: object
      properties:
        id:
          type: integer
          format: int64
          minimum: 1
          example: 1
        title:
          type: string
          example: 星を継ぐもの
        titleKana:
          type: string
          example: ホシヲツグモノ
        author:
          type: string
          example: ジェイムズ・P・ホーガン
        publisherId:
          type: integer
          format: int64
          minimum: 1
          example: 1
        userId:
          type: integer
          format: int64
          minimum: 1
          example: 1
      required:
        - id
    BooksDelete:
      type: object
      description: 書籍情報一括削除用のデータオブジェクト
      properties:
        ids:
          type: array
          items:
            type: integer
            format: int64
            minimum: 1
          example:
            - 1
            - 2
      required:
        - ids
    Error:
      type: object
      properties:
        code:
          type: string
          example: 500
        message:
          type: string
          example: 予想外のエラーが発生しました。 エラー内容：...
      required:
        - code
        - message