@startuml deleteBook

title 書籍データの削除 (Delete - 論理削除)

actor ":User" as User
participant "UI" as UI
boundary ":BookController" as BookController
control ":BookService" as BookService
entity ":BookMapper" as BookMapper
database ":DB" as DB

activate User
User -> UI ++ : 削除ボタン
UI -> BookController ++ : request (DELETE /books/{bookID})
BookController -> BookService ++ : bookId
BookService -> BookMapper ++ : bookId
BookMapper -> DB ++ : UPDATE実行
alt DB更新が失敗したとき
    DB --> BookMapper : 更新失敗
    BookMapper --> BookService : 更新失敗
    BookService --> BookController : 削除失敗
    BookController --> UI : 削除失敗
    UI --> User : 削除失敗
end
DB --> BookMapper -- : 更新成功
BookMapper --> BookService -- : 削除成功
BookService --> BookController -- : 削除完了
BookController --> UI -- : 削除成功
UI --> User -- : 削除完了
deactivate User

@enduml