@startuml deleteBooks

title 書籍データの一括削除 (Batch Delete - 論理削除)

actor ":User" as User
participant "UI" as UI
boundary ":BookController" as BookController
control ":BookService" as BookService
entity ":BookMapper" as BookMapper
database ":DB" as DB

activate User
User -> UI ++ : 一括削除
UI -> BookController ++ : (DELETE /books/batch json:ids)
BookController -> BookService ++ : book ids
note over BookService : @transaction
BookService -> BookMapper ++ : book ids
BookMapper -> DB ++ : UPDATE

alt 削除失敗した場合
    DB --> BookMapper : error
    BookMapper --> BookService : error
    note over BookService : rollback
    BookService --> BookController : error
    BookController --> UI : error
    UI --> User : 結果表示
end

DB --> BookMapper -- : 影響件数
BookMapper --> BookService -- : 影響件数
note over BookService : commit
BookService --> BookController -- : 削除結果
BookController --> UI -- : 削除結果
UI --> User -- : 結果表示
deactivate User

@enduml