@startuml registerBook

title 書籍データの新規登録 (Create)

actor ":User" as User
participant "UI" as UI
boundary ":BookController" as BookController
control ":BookService" as BookService
entity ":BookMapper" as BookMapper
database ":DB" as DB

activate User
User -> UI ++ : 情報登録
UI -> BookController ++ : POST /books
BookController -> BookService ++ : Book
BookService -> BookMapper ++ : Book
BookMapper -> DB ++ : INSERT...

alt 新規登録失敗した場合
    DB --> BookMapper : 影響件数0
    BookMapper --> BookService : 影響件数0
    BookService --> BookController : 登録失敗
    BookController --> UI : 登録失敗
    UI --> User : 登録失敗
end

DB --> BookMapper -- : 影響件数1
BookMapper --> BookService -- : 影響件数1
BookService --> BookController -- : 登録完了
BookController --> UI -- : 登録成功
UI --> User -- : 登録完了
deactivate User

@enduml