@startuml registerBooks

title 書籍データの一括登録

actor ":User" as User
participant "UI" as UI
boundary ":BookController" as BookController
control ":BookService" as BookService
entity ":BookMapper" as BookMapper
database ":DB" as DB

activate User
User -> UI ++ : 一括登録
UI -> BookController ++ : request (POST /books, JSON)
BookController -> BookService ++ : List<BookCreate>
note over BookService : @transaction
BookService -> BookMapper ++ : 一括保存依頼
BookMapper -> DB ++ : 一括INSERT

alt 全て登録できなかった場合
    DB --> BookMapper : 追加された件数
    BookMapper --> BookService : 追加された件数一致しない
    note over BookService : rollback
    BookService --> BookController : 失敗
    BookController --> UI : 失敗
    UI --> User : 失敗表示
end

DB --> BookMapper -- : 追加された件数
BookMapper --> BookService -- : 追加された件数
note over BookService : commit
BookService --> BookController -- : 追加された件数
BookController --> UI -- : 追加された件数
UI --> User -- : 結果表示
deactivate User

@enduml