@startuml updateBook

title 書籍データの更新 (Update)

actor ":User" as User
participant "UI" as UI
boundary ":BookController" as BookController
control ":BookService" as BookService
entity ":BookMapper" as BookMapper
database ":DB" as DB

activate User
User -> UI ++ : 情報更新請求
UI -> BookController ++ : (PUT /books/{id}, json)
BookController -> BookService ++ : book
BookService -> BookMapper ++ : book
BookMapper -> DB ++ : UPDATE
DB --> BookMapper -- : 更新成功(ids)
BookMapper --> BookService -- : 更新成功
BookService --> BookController -- : 更新完了
BookController --> UI -- : 更新成功レスポンス (ids)
UI --> User -- : 更新完了画面を表示
deactivate User

@enduml